kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: spark-worker
spec:
  replicas: 5
  selector:
    matchLabels:
      component: spark-worker
  template:
    metadata:
      labels:
        component: spark-worker
    spec:
      containers:
        - name: spark-worker
          image: spark-hadoop:1.0.36
          command: ["./run-worker.sh"]
          ports:
            - containerPort: 8085
            - containerPort: 2222
            - containerPort: 4040
          #lifecycle:
          #  postStart:
          #    exec:
          #      command: ["/bin/sh", "-c", "echo spark.driver.bindAddress $MY_POD_IP >> /opt/spark/conf/spark-defaults.conf"]
          terminationMessagePolicy: FallbackToLogsOnError
          env:
          - name: SPARK_WORKER_WEBUI_PORT
            value: "8085"
          - name: SPARK_WORKER_PORT
            value: "2222" 
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          resources:
            requests:
              cpu: 100m
          volumeMounts:
#          - name: datadir
#            mountPath: /opt/spark/data/
          - name: varlog
            mountPath: /opt/spark/logs/  
      volumes:
        - name: varlog
          hostPath:
            # directory location on host
            path: /tmp/logs
            # this field is optional
            type: Directory
#        - name: datadir
#          hostPath:
#            # directory location on host
#            path: /Users/etulika/Projects/spark-2.4.3-bin-hadoop2.7/datafiles/
#            # this field is optional
#            type: Directory
